import javax.swing.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author creui
 */
public class Appointments extends javax.swing.JPanel {
	JPanel contentPane;
	AMS AMS;
	DefaultTableModel appointmentsModel;
	CardLayout layout;

	/**
	 * Creates new form Appointments
	 */
	public Appointments(JPanel contentPane, AMS scheduler) {
		this.contentPane = contentPane;
		this.AMS = scheduler;

		appointmentsModel = new DefaultTableModel();

		appointmentsModel.addColumn("Schedule");
		appointmentsModel.addColumn("Property");
		appointmentsModel.addColumn("Client");

		layout = (CardLayout) contentPane.getLayout();

		initComponents();

		updateViewerAppointments(1); // TEMPORARY MAGIC VALUE

		sortBy.addItem("Property");
		sortBy.addItem("Customer");
		sortBy.addItem("Schedule");
	}

	private void updateViewerAppointments(int agentID) {
		DefaultTableModel model = (DefaultTableModel) viewer.getModel();
		model.setRowCount(0);

		appointmentsModel = AMS.getAppointments(appointmentsModel, agentID);

		viewer.setModel(appointmentsModel);
		viewer.doLayout();
	} 

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                userLabel = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                viewer = new javax.swing.JTable();
                filterBy = new javax.swing.JComboBox<>();
                filterByLabel = new javax.swing.JLabel();
                sortByLabel = new javax.swing.JLabel();
                sortBy = new javax.swing.JComboBox<>();
                addPropertyButton = new javax.swing.JButton();
                addLabel = new javax.swing.JLabel();
                addCustomerButton = new javax.swing.JButton();
                addAppointmentButton = new javax.swing.JButton();
                logoutButton = new javax.swing.JButton();
                listByLabel = new javax.swing.JLabel();
                listBy = new javax.swing.JComboBox<>();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();

                setMinimumSize(new java.awt.Dimension(720, 576));
                setPreferredSize(new java.awt.Dimension(720, 576));
                addComponentListener(new java.awt.event.ComponentAdapter() {
                        public void componentShown(java.awt.event.ComponentEvent evt) {
                                formComponentShown(evt);
                        }
                });
                setLayout(new java.awt.GridBagLayout());

                userLabel.setText("User");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                gridBagConstraints.insets = new java.awt.Insets(40, 20, 0, 0);
                add(userLabel, gridBagConstraints);

                viewer.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null}
                        },
                        new String [] {
                                "Property", "Customer", "Schedule"
                        }
                ));
                jScrollPane1.setViewportView(viewer);

                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.gridwidth = 6;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.weighty = 1.0;
                gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
                add(jScrollPane1, gridBagConstraints);

                filterBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Property", "Client", "Day", "Time" }));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 3;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 20);
                add(filterBy, gridBagConstraints);

                filterByLabel.setText("Filter by...");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
                gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 20);
                add(filterByLabel, gridBagConstraints);

                sortByLabel.setText("Sort by...");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 4;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
                gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 20);
                add(sortByLabel, gridBagConstraints);

                sortBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Property", "Client", "Day", "Time" }));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 5;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 20);
                add(sortBy, gridBagConstraints);

                addPropertyButton.setText("Property");
                addPropertyButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addPropertyButtonActionPerformed(evt);
                        }
                });
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 3;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.insets = new java.awt.Insets(0, 0, 40, 20);
                add(addPropertyButton, gridBagConstraints);

                addLabel.setText("Add...");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
                gridBagConstraints.insets = new java.awt.Insets(0, 0, 40, 20);
                add(addLabel, gridBagConstraints);

                addCustomerButton.setText("Customer");
                addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addCustomerButtonActionPerformed(evt);
                        }
                });
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 4;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.insets = new java.awt.Insets(0, 0, 40, 20);
                add(addCustomerButton, gridBagConstraints);

                addAppointmentButton.setText("Appointment");
                addAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addAppointmentButtonActionPerformed(evt);
                        }
                });
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 5;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.insets = new java.awt.Insets(0, 0, 40, 20);
                add(addAppointmentButton, gridBagConstraints);

                logoutButton.setText("Log out");
                logoutButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                logoutButtonActionPerformed(evt);
                        }
                });
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                gridBagConstraints.weightx = 1.0;
                gridBagConstraints.insets = new java.awt.Insets(40, 20, 0, 20);
                add(logoutButton, gridBagConstraints);

                listByLabel.setText("List...");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 4;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
                gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
                add(listByLabel, gridBagConstraints);

                listBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appointments", "Properties", "Clients" }));
                listBy.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                listByActionPerformed(evt);
                        }
                });
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 5;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
                add(listBy, gridBagConstraints);

                jButton1.setText("Edit");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 0);
                add(jButton1, gridBagConstraints);

                jButton2.setText("Remove");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(0, 20, 40, 0);
                add(jButton2, gridBagConstraints);
        }// </editor-fold>//GEN-END:initComponents

        private void listByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listByActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_listByActionPerformed

        private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
		userLabel.setText(AMS.getAgentName(Main.sessionAgent));
        }//GEN-LAST:event_formComponentShown

        private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
                Main.sessionAgent = null;
		Main.sessionAgentID = 0;
		layout.show(contentPane, "Log in");
        }//GEN-LAST:event_logoutButtonActionPerformed

        private void addPropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPropertyButtonActionPerformed
		layout.show(contentPane, "Add Property");
        }//GEN-LAST:event_addPropertyButtonActionPerformed

        private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
		layout.show(contentPane, "Add Client");
        }//GEN-LAST:event_addCustomerButtonActionPerformed

        private void addAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAppointmentButtonActionPerformed
		layout.show(contentPane, "Add Appointment");
        }//GEN-LAST:event_addAppointmentButtonActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton addAppointmentButton;
        private javax.swing.JButton addCustomerButton;
        private javax.swing.JLabel addLabel;
        private javax.swing.JButton addPropertyButton;
        private javax.swing.JComboBox<String> filterBy;
        private javax.swing.JLabel filterByLabel;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JComboBox<String> listBy;
        private javax.swing.JLabel listByLabel;
        private javax.swing.JButton logoutButton;
        private javax.swing.JComboBox<String> sortBy;
        private javax.swing.JLabel sortByLabel;
        private javax.swing.JLabel userLabel;
        private javax.swing.JTable viewer;
        // End of variables declaration//GEN-END:variables
}
