
import java.awt.CardLayout;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author creui
 */
public class Login extends javax.swing.JPanel {
	AMS AMS;
	JPanel contentPane;

	/**
	 * Creates new form Login
	 */
	public Login(JPanel contentPane, AMS scheduler) {
		this.AMS = scheduler;
		this.contentPane = contentPane;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                userLabel = new javax.swing.JLabel();
                userField = new javax.swing.JTextField();
                passwordLabel = new javax.swing.JLabel();
                passwordField = new javax.swing.JPasswordField();
                loginButton = new javax.swing.JButton();
                registerButton = new javax.swing.JButton();

                setMinimumSize(new java.awt.Dimension(720, 576));
                setPreferredSize(new java.awt.Dimension(720, 576));
                setLayout(new java.awt.GridBagLayout());

                userLabel.setText("User");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
                gridBagConstraints.weightx = 0.5;
                add(userLabel, gridBagConstraints);

                userField.setColumns(36);
                userField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                userFieldActionPerformed(evt);
                        }
                });
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                gridBagConstraints.weightx = 0.5;
                gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
                add(userField, gridBagConstraints);

                passwordLabel.setText("Password");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
                gridBagConstraints.weightx = 0.5;
                add(passwordLabel, gridBagConstraints);

                passwordField.setColumns(36);
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                gridBagConstraints.weightx = 0.5;
                gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
                add(passwordField, gridBagConstraints);

                loginButton.setText("Log in");
                loginButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loginButtonActionPerformed(evt);
                        }
                });
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.gridwidth = 2;
                add(loginButton, gridBagConstraints);

                registerButton.setText("Register");
                registerButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                registerButtonActionPerformed(evt);
                        }
                });
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
                add(registerButton, gridBagConstraints);
        }// </editor-fold>//GEN-END:initComponents

        private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_userFieldActionPerformed

        private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
		CardLayout layout = (CardLayout) contentPane.getLayout();
		layout.show(contentPane, "Register");
        }//GEN-LAST:event_registerButtonActionPerformed

        private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
		if (AMS.validateAgent(userField.getText(), passwordField.getText())) {
			Main.sessionAgent = userField.getText();
			Main.sessionAgentID = AMS.getAgentID(Main.sessionAgent);
			CardLayout layout = (CardLayout) contentPane.getLayout();
			layout.show(contentPane, "Appointments");
			userField.setText("");
			passwordField.setText("");
		}
        }//GEN-LAST:event_loginButtonActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton loginButton;
        private javax.swing.JPasswordField passwordField;
        private javax.swing.JLabel passwordLabel;
        private javax.swing.JButton registerButton;
        private javax.swing.JTextField userField;
        private javax.swing.JLabel userLabel;
        // End of variables declaration//GEN-END:variables
}
